"""initial schema

Revision ID: 77d2af391dc4
Revises: 
Create Date: 2026-07-29 13:18:37.818834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d2af391dc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if 'rule_conditions' in existing_tables:
        op.drop_table('rule_conditions')
    if 'rules' in existing_tables:
        op.drop_table('rules')
    # SQLite does not support ALTER COLUMN, so we keep the existing table definitions
    # and rely on the current schema already matching the ORM model.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.TEXT(), nullable=False),
    sa.Column('withholding_rate', sa.REAL(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_conditions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('rule_id', sa.INTEGER(), nullable=False),
    sa.Column('condition_type', sa.TEXT(), nullable=False),
    sa.Column('operator', sa.TEXT(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
